package com.github.edgar615.nef.param.entity;

import com.github.edgar615.entity.Persistent;
import com.google.common.base.MoreObjects;

/**
* This class is generated by Jdbc code generator.
*
* Table : param_group
* remarks: 参数分组
*
* @author Jdbc Code Generator
*/
public class ParamGroup implements Persistent<Long> {

    private static final long serialVersionUID = 7871577886617269920L;
    
    /**
    * Column : param_group_id
    * remarks: 参数分组id
    * default: 
    * isNullable: false
    * isAutoInc: false
    * isPrimary: true
    * type: -5
    * size: 19
    */
    private Long paramGroupId;
    
    /**
    * Column : type
    * remarks: 类型
    * default: 
    * isNullable: true
    * isAutoInc: false
    * isPrimary: false
    * type: -6
    * size: 3
    */
    private Integer type;
    
    /**
    * Column : name
    * remarks: 名称
    * default: 
    * isNullable: true
    * isAutoInc: false
    * isPrimary: false
    * type: 12
    * size: 32
    */
    private String name;
    
    /**
    * Column : alias
    * remarks: 别名
    * default: 
    * isNullable: true
    * isAutoInc: false
    * isPrimary: false
    * type: 12
    * size: 32
    */
    private String alias;
    
    /**
    * Column : sorted
    * remarks: 显示顺序
    * default: 
    * isNullable: true
    * isAutoInc: false
    * isPrimary: false
    * type: 4
    * size: 10
    */
    private Integer sorted;
    
    /**
    * Column : create_time
    * remarks: 创建时间
    * default: 
    * isNullable: true
    * isAutoInc: false
    * isPrimary: false
    * type: -5
    * size: 19
    */
    private Long createTime;
    
    /**
    * Column : update_time
    * remarks: 修改时间
    * default: 
    * isNullable: true
    * isAutoInc: false
    * isPrimary: false
    * type: -5
    * size: 19
    */
    private Long updateTime;
    
    public Long getParamGroupId() {
        return paramGroupId;
    }

    public void setParamGroupId(Long paramGroupId) {
        this.paramGroupId = paramGroupId;
    }
    
    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }
    
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
    
    public String getAlias() {
        return alias;
    }

    public void setAlias(String alias) {
        this.alias = alias;
    }
    
    public Integer getSorted() {
        return sorted;
    }

    public void setSorted(Integer sorted) {
        this.sorted = sorted;
    }
    
    public Long getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }
    
    public Long getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }
    
    @Override
    public String toString() {
        return MoreObjects.toStringHelper("ParamGroup")
            .add("paramGroupId",  paramGroupId)
            .add("type",  type)
            .add("name",  name)
            .add("alias",  alias)
            .add("sorted",  sorted)
            .add("createTime",  createTime)
            .add("updateTime",  updateTime)
           .toString();
    }

    @Override
    public Long id () {
    return paramGroupId;
    }

    @Override
    public void setId(Long id) {
        this.paramGroupId = id;
    }

    @Override
    public void setGeneratedKey(Number key) {
    
        this.paramGroupId = key.longValue();
    
    }

   /* START Do not remove/edit this line. CodeGenerator will preserve any code between start and end tags.*/
	/* END Do not remove/edit this line. CodeGenerator will preserve any code between start and end tags.*/
}
