package com.github.edgar615.nef.param.entity;

import com.github.edgar615.entity.PersistentKit;
import com.google.common.collect.Lists;
import java.util.List;
import java.util.Map;

/**
* This class is generated by Jdbc code generator.
*
* Table : param_value
*
* @author Jdbc Code Generator
*/
public class ParamValueKit implements PersistentKit<Long, ParamValue> {

    private static final long serialVersionUID = 1L;
    
    public static final String DB_PARAM_VALUE_ID = "param_value_id";
    
    public static final String DB_PARAM_DEF_ID = "param_def_id";
    
    public static final String DB_PARAM_VALUE = "param_value";
    
    public static final String DB_APPLICATION_ID = "application_id";
    
    public static final String DB_SUBJECT_ID = "subject_id";
    
    public static final String DB_CREATE_TIME = "create_time";
    
    public static final String DB_UPDATE_TIME = "update_time";
    
    
    public static final String PARAM_VALUE_ID = "paramValueId";
    
    public static final String PARAM_DEF_ID = "paramDefId";
    
    public static final String PARAM_VALUE = "paramValue";
    
    public static final String APPLICATION_ID = "applicationId";
    
    public static final String SUBJECT_ID = "subjectId";
    
    public static final String CREATE_TIME = "createTime";
    
    public static final String UPDATE_TIME = "updateTime";
    
    @Override
    public List<String> fields() {
      return Lists.newArrayList(PARAM_VALUE_ID,
						PARAM_DEF_ID,
						PARAM_VALUE,
						APPLICATION_ID,
						SUBJECT_ID,
						CREATE_TIME,
						UPDATE_TIME);
    }
    
    
    @Override
    public String primaryField() {
        return PARAM_VALUE_ID;
    }

    @Override
    public void toMap(ParamValue paramValue, Map<String, Object> map) {
        if (map == null) {
            return;
        }
        
        map.put(PARAM_VALUE_ID,  paramValue.getParamValueId());
        map.put(PARAM_DEF_ID,  paramValue.getParamDefId());
        map.put(PARAM_VALUE,  paramValue.getParamValue());
        map.put(APPLICATION_ID,  paramValue.getApplicationId());
        map.put(SUBJECT_ID,  paramValue.getSubjectId());
        map.put(CREATE_TIME,  paramValue.getCreateTime());
        map.put(UPDATE_TIME,  paramValue.getUpdateTime());
    }

    @Override
    public void fromMap(Map<String, Object> map, ParamValue paramValue) {
        if (map == null) {
            return;
        }
        if (map.get(PARAM_VALUE_ID) instanceof Long) {
            paramValue.setParamValueId((Long) map.get(PARAM_VALUE_ID));
        }
        if (map.get(PARAM_DEF_ID) instanceof Long) {
            paramValue.setParamDefId((Long) map.get(PARAM_DEF_ID));
        }
        if (map.get(PARAM_VALUE) instanceof String) {
            paramValue.setParamValue((String) map.get(PARAM_VALUE));
        }
        if (map.get(APPLICATION_ID) instanceof Long) {
            paramValue.setApplicationId((Long) map.get(APPLICATION_ID));
        }
        if (map.get(SUBJECT_ID) instanceof Long) {
            paramValue.setSubjectId((Long) map.get(SUBJECT_ID));
        }
        if (map.get(CREATE_TIME) instanceof Long) {
            paramValue.setCreateTime((Long) map.get(CREATE_TIME));
        }
        if (map.get(UPDATE_TIME) instanceof Long) {
            paramValue.setUpdateTime((Long) map.get(UPDATE_TIME));
        }
        
    }

   /* START Do not remove/edit this line. CodeGenerator will preserve any code between start and end tags.*/
	/* END Do not remove/edit this line. CodeGenerator will preserve any code between start and end tags.*/
}
