package com.github.edgar615.nef.param.entity;

import com.github.edgar615.entity.Persistent;
import com.google.common.base.MoreObjects;

/**
* This class is generated by Jdbc code generator.
*
* Table : param_option
* remarks: 参数选项
*
* @author Jdbc Code Generator
*/
public class ParamOption implements Persistent<Long> {

    private static final long serialVersionUID = -5493564873119976736L;
    
    /**
    * Column : param_option_id
    * remarks: 参数选项id
    * default: 
    * isNullable: false
    * isAutoInc: false
    * isPrimary: true
    * type: -5
    * size: 19
    */
    private Long paramOptionId;
    
    /**
    * Column : param_def_id
    * remarks: 属性id
    * default: 
    * isNullable: true
    * isAutoInc: false
    * isPrimary: false
    * type: -5
    * size: 19
    */
    private Long paramDefId;
    
    /**
    * Column : option_text
    * remarks: 属性文本
    * default: 
    * isNullable: true
    * isAutoInc: false
    * isPrimary: false
    * type: 12
    * size: 16
    */
    private String optionText;
    
    /**
    * Column : option_value
    * remarks: 属性值
    * default: 
    * isNullable: true
    * isAutoInc: false
    * isPrimary: false
    * type: 4
    * size: 10
    */
    private Integer optionValue;
    
    /**
    * Column : sorted
    * remarks: 显示顺序
    * default: 
    * isNullable: true
    * isAutoInc: false
    * isPrimary: false
    * type: 4
    * size: 10
    */
    private Integer sorted;
    
    public Long getParamOptionId() {
        return paramOptionId;
    }

    public void setParamOptionId(Long paramOptionId) {
        this.paramOptionId = paramOptionId;
    }
    
    public Long getParamDefId() {
        return paramDefId;
    }

    public void setParamDefId(Long paramDefId) {
        this.paramDefId = paramDefId;
    }
    
    public String getOptionText() {
        return optionText;
    }

    public void setOptionText(String optionText) {
        this.optionText = optionText;
    }
    
    public Integer getOptionValue() {
        return optionValue;
    }

    public void setOptionValue(Integer optionValue) {
        this.optionValue = optionValue;
    }
    
    public Integer getSorted() {
        return sorted;
    }

    public void setSorted(Integer sorted) {
        this.sorted = sorted;
    }
    
    @Override
    public String toString() {
        return MoreObjects.toStringHelper("ParamOption")
            .add("paramOptionId",  paramOptionId)
            .add("paramDefId",  paramDefId)
            .add("optionText",  optionText)
            .add("optionValue",  optionValue)
            .add("sorted",  sorted)
           .toString();
    }

    @Override
    public Long id () {
    return paramOptionId;
    }

    @Override
    public void setId(Long id) {
        this.paramOptionId = id;
    }

    @Override
    public void setGeneratedKey(Number key) {
    
        this.paramOptionId = key.longValue();
    
    }

   /* START Do not remove/edit this line. CodeGenerator will preserve any code between start and end tags.*/
	/* END Do not remove/edit this line. CodeGenerator will preserve any code between start and end tags.*/
}
