package com.github.edgar615.nef.param.entity;

import com.github.edgar615.util.validation.Rule;
import com.google.common.collect.ArrayListMultimap;
import com.google.common.collect.Multimap;

/**
* This class is generated by Jdbc code generator.
*
* Table : param_group
*
* @author Jdbc Code Generator
*/
public class ParamGroupRule {

    /**
    * 根据数据库生成的最长长度校验
    *
    * @return Multimap<String, Rule>
    */
    public static Multimap<String, Rule> maxLengthRule() {
        Multimap<String, Rule> rules = ArrayListMultimap.create();
        rules.put("name",  Rule.maxLength(32));
        rules.put("alias",  Rule.maxLength(32));
        return rules;
    }

    /**
    * 根据数据库生成的必填项校验。
    * 在实际接口开发中，有些必填项是没有的，例如自动生成的主键开始会设置为null
    *
    * @return Multimap<String, Rule>
    */
    public static Multimap<String, Rule> requiredRule() {
        Multimap<String, Rule> rules = ArrayListMultimap.create();
        
        rules.put("paramGroupId", Rule.required());
        return rules;
    }

   /* START Do not remove/edit this line. CodeGenerator will preserve any code between start and end tags.*/
	/* END Do not remove/edit this line. CodeGenerator will preserve any code between start and end tags.*/


}
