package com.github.edgar615.nef.param.dao.impl;

import com.github.edgar615.dao.BaseDaoImpl;
import com.github.edgar615.jdbc.Jdbc;
import com.github.edgar615.nef.param.dao.ParamDefDao;
import com.github.edgar615.nef.param.entity.ParamDef;
import java.util.List;
import org.springframework.stereotype.Service;

/**
* This class is generated by Jdbc code generator.
*
* Table : param_def
*
* @author Jdbc Code Generator
*/
@Service
public class ParamDefDaoImpl extends BaseDaoImpl<Long, ParamDef> implements ParamDefDao {
    
    public ParamDefDaoImpl(Jdbc jdbc) {
        super(ParamDef.class, jdbc);
    }
    

    /* START Do not remove/edit this line. CodeGenerator will preserve any code between start and end tags.*/

    @Override
    public List<ParamDef> findByGroup(long paramGroupId) {
        return null;
    }
	/* END Do not remove/edit this line. CodeGenerator will preserve any code between start and end tags.*/


}
