package com.github.edgar615.nef.param.dao.impl;

import com.github.edgar615.dao.BaseDaoImpl;
import com.github.edgar615.jdbc.Jdbc;
import com.github.edgar615.nef.param.dao.ParamValueDao;
import com.github.edgar615.nef.param.entity.ParamValue;
import org.springframework.stereotype.Service;

/**
* This class is generated by Jdbc code generator.
*
* Table : param_value
*
* @author Jdbc Code Generator
*/
@Service
public class ParamValueDaoImpl extends BaseDaoImpl<Long, ParamValue> implements ParamValueDao {
    
    public ParamValueDaoImpl(Jdbc jdbc) {
        super(ParamValue.class, jdbc);
    }
    

    /* START Do not remove/edit this line. CodeGenerator will preserve any code between start and end tags.*/

    @Override
    public void deleteByDef(long defId) {

    }
	/* END Do not remove/edit this line. CodeGenerator will preserve any code between start and end tags.*/


}
