package com.github.edgar615.nef.param.dao.impl;

import com.github.edgar615.dao.BaseDaoImpl;
import com.github.edgar615.jdbc.Jdbc;
import com.github.edgar615.nef.param.dao.ParamOptionDao;
import com.github.edgar615.nef.param.entity.ParamOption;
import org.springframework.stereotype.Service;

/**
* This class is generated by Jdbc code generator.
*
* Table : param_option
*
* @author Jdbc Code Generator
*/
@Service
public class ParamOptionDaoImpl extends BaseDaoImpl<Long, ParamOption> implements ParamOptionDao {
    
    public ParamOptionDaoImpl(Jdbc jdbc) {
        super(ParamOption.class, jdbc);
    }
    

    /* START Do not remove/edit this line. CodeGenerator will preserve any code between start and end tags.*/
	/* END Do not remove/edit this line. CodeGenerator will preserve any code between start and end tags.*/
}
