package com.github.edgar615.nef.param.dao;

import com.github.edgar615.dao.BaseDao;
import com.github.edgar615.nef.param.entity.ParamDef;
import java.util.List;

/**
* This class is generated by Jdbc code generator.
*
* Table : param_def
*
* @author Jdbc Code Generator
*/
public interface ParamDefDao extends BaseDao<Long, ParamDef> {

   /* START Do not remove/edit this line. CodeGenerator will preserve any code between start and end tags.*/
  List<ParamDef> findByGroup(long paramGroupId);
	/* END Do not remove/edit this line. CodeGenerator will preserve any code between start and end tags.*/


}
