package com.github.edgar615.nef.param.dao;

import com.github.edgar615.dao.BaseDao;
import com.github.edgar615.nef.param.entity.ParamValue;

/**
* This class is generated by Jdbc code generator.
*
* Table : param_value
*
* @author Jdbc Code Generator
*/
public interface ParamValueDao extends BaseDao<Long, ParamValue> {

  /* START Do not remove/edit this line. CodeGenerator will preserve any code between start and end tags.*/
  /**
   * 根据def删除option
   * @param defId
   */
  void deleteByDef(long defId);
	/* END Do not remove/edit this line. CodeGenerator will preserve any code between start and end tags.*/
}
