package com.github.edgar615.nef.param.dao;

import com.github.edgar615.dao.BaseDao;
import com.github.edgar615.nef.param.entity.ParamOption;
import java.util.List;

/**
* This class is generated by Jdbc code generator.
*
* Table : param_option
*
* @author Jdbc Code Generator
*/
public interface ParamOptionDao extends BaseDao<Long, ParamOption> {

   /* START Do not remove/edit this line. CodeGenerator will preserve any code between start and end tags.*/

  /**
   * 根据def删除option
   * @param defId
   */
  void deleteByDef(long defId);

  /**
   * 根据def查找option
   * @param defId
   * @return
   */
  List<ParamOption> findByDef(long defId);
  /* END Do not remove/edit this line. CodeGenerator will preserve any code between start and end tags.*/


}
