package com.github.edgar615.nef.param.dao;

import com.github.edgar615.dao.BaseDao;
import com.github.edgar615.nef.param.entity.ParamGroup;

/**
* This class is generated by Jdbc code generator.
*
* Table : param_group
*
* @author Jdbc Code Generator
*/
public interface ParamGroupDao extends BaseDao<Long, ParamGroup> {

   /* START Do not remove/edit this line. CodeGenerator will preserve any code between start and end tags.*/
  Long findByName(String paramGroup);
	/* END Do not remove/edit this line. CodeGenerator will preserve any code between start and end tags.*/


}
